#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tmds.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tmdsDatabaseDynamic")]
	public partial class TmdsDynamicDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblTrackTagsActive(tblTrackTagsActive instance);
    partial void UpdatetblTrackTagsActive(tblTrackTagsActive instance);
    partial void DeletetblTrackTagsActive(tblTrackTagsActive instance);
    #endregion
		
		public TmdsDynamicDataContext() : 
				base(global::Tmds.Properties.Settings.Default.tmdsDatabaseDynamicConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TmdsDynamicDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TmdsDynamicDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TmdsDynamicDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TmdsDynamicDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblTrackTagsActive> tblTrackTagsActives
		{
			get
			{
				return this.GetTable<tblTrackTagsActive>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTrackTagsActive")]
	public partial class tblTrackTagsActive : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TrackGUID;
		
		private string _Subdivision;
		
		private System.Nullable<int> _TerritoryID;
		
		private string _Creator;
		
		private string _CreateTime;
		
		private string _TagType;
		
		private string _DataString;
		
		private System.Nullable<int> _Restrictive;
		
		private bool _RestrictionFlag;
		
		private string _DelayData;
		
		private bool _Delay;
		
		private string _TagUID;
		
		private string _Direction;
		
		private System.Nullable<System.DateTime> _ExpectedReleaseTime;
		
		private string _CompList;
		
		private System.Nullable<int> _RefNumPTC;
		
		private string _PTCData;
		
		private string _NameRequestingTagPlacement;
		
		private string _SpeedTagFlagInfo;
		
		private string _SpeedTagReasonCode;
		
		private System.Nullable<bool> _CreateSpeedRestriction;
		
		private System.Nullable<bool> _SpeedRestrictionCreated;
		
		private System.Nullable<System.DateTime> _DurationTime;
		
		private System.Nullable<bool> _BulletinTag;
		
		private string _BulletinReferenceGUID;
		
		private System.Nullable<bool> _BulletinForProtectionList;
		
		private System.Nullable<bool> _BulletinForCancellationList;
		
		private string _PTCComponents;
		
		private string _PTCTrackSegments;
		
		private string _PTCBulletinText;
		
		private string _MilePostBeginPrefix;
		
		private string _MilePostEndPrefix;
		
		private string _DeliveryOfRestriction;
		
		private string _AdvisorySummary;
		
		private string _MilePostBeginSuffix;
		
		private string _MilePostEndSuffix;
		
		private string _MilePostBegin;
		
		private string _MilePostEnd;
		
		private System.Nullable<long> _PTCCompositionCRC;
		
		private System.Nullable<long> _ObjectCRC;
		
		private System.Nullable<bool> _AutoTag;
		
		private System.Nullable<int> _TerritoryID2;
		
		private System.Nullable<int> _TerritoryID3;
		
		private string _CompList2;
		
		private string _CompList3;
		
		private string _FlagCompList1;
		
		private string _FlagCompList2;
		
		private string _FlagCompList3;
		
		private string _BorderFlagSubs;
		
		private string _BorderFlagCompList;
		
		private string _AutoTagStatus;
		
		private System.Nullable<bool> _CriticalAlertType;
		
		private bool _IsPTCEnforceable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrackGUIDChanging(int value);
    partial void OnTrackGUIDChanged();
    partial void OnSubdivisionChanging(string value);
    partial void OnSubdivisionChanged();
    partial void OnTerritoryIDChanging(System.Nullable<int> value);
    partial void OnTerritoryIDChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateTimeChanging(string value);
    partial void OnCreateTimeChanged();
    partial void OnTagTypeChanging(string value);
    partial void OnTagTypeChanged();
    partial void OnDataStringChanging(string value);
    partial void OnDataStringChanged();
    partial void OnRestrictiveChanging(System.Nullable<int> value);
    partial void OnRestrictiveChanged();
    partial void OnRestrictionFlagChanging(bool value);
    partial void OnRestrictionFlagChanged();
    partial void OnDelayDataChanging(string value);
    partial void OnDelayDataChanged();
    partial void OnDelayChanging(bool value);
    partial void OnDelayChanged();
    partial void OnTagUIDChanging(string value);
    partial void OnTagUIDChanged();
    partial void OnDirectionChanging(string value);
    partial void OnDirectionChanged();
    partial void OnExpectedReleaseTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnExpectedReleaseTimeChanged();
    partial void OnCompListChanging(string value);
    partial void OnCompListChanged();
    partial void OnRefNumPTCChanging(System.Nullable<int> value);
    partial void OnRefNumPTCChanged();
    partial void OnPTCDataChanging(string value);
    partial void OnPTCDataChanged();
    partial void OnNameRequestingTagPlacementChanging(string value);
    partial void OnNameRequestingTagPlacementChanged();
    partial void OnSpeedTagFlagInfoChanging(string value);
    partial void OnSpeedTagFlagInfoChanged();
    partial void OnSpeedTagReasonCodeChanging(string value);
    partial void OnSpeedTagReasonCodeChanged();
    partial void OnCreateSpeedRestrictionChanging(System.Nullable<bool> value);
    partial void OnCreateSpeedRestrictionChanged();
    partial void OnSpeedRestrictionCreatedChanging(System.Nullable<bool> value);
    partial void OnSpeedRestrictionCreatedChanged();
    partial void OnDurationTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDurationTimeChanged();
    partial void OnBulletinTagChanging(System.Nullable<bool> value);
    partial void OnBulletinTagChanged();
    partial void OnBulletinReferenceGUIDChanging(string value);
    partial void OnBulletinReferenceGUIDChanged();
    partial void OnBulletinForProtectionListChanging(System.Nullable<bool> value);
    partial void OnBulletinForProtectionListChanged();
    partial void OnBulletinForCancellationListChanging(System.Nullable<bool> value);
    partial void OnBulletinForCancellationListChanged();
    partial void OnPTCComponentsChanging(string value);
    partial void OnPTCComponentsChanged();
    partial void OnPTCTrackSegmentsChanging(string value);
    partial void OnPTCTrackSegmentsChanged();
    partial void OnPTCBulletinTextChanging(string value);
    partial void OnPTCBulletinTextChanged();
    partial void OnMilePostBeginPrefixChanging(string value);
    partial void OnMilePostBeginPrefixChanged();
    partial void OnMilePostEndPrefixChanging(string value);
    partial void OnMilePostEndPrefixChanged();
    partial void OnDeliveryOfRestrictionChanging(string value);
    partial void OnDeliveryOfRestrictionChanged();
    partial void OnAdvisorySummaryChanging(string value);
    partial void OnAdvisorySummaryChanged();
    partial void OnMilePostBeginSuffixChanging(string value);
    partial void OnMilePostBeginSuffixChanged();
    partial void OnMilePostEndSuffixChanging(string value);
    partial void OnMilePostEndSuffixChanged();
    partial void OnMilePostBeginChanging(string value);
    partial void OnMilePostBeginChanged();
    partial void OnMilePostEndChanging(string value);
    partial void OnMilePostEndChanged();
    partial void OnPTCCompositionCRCChanging(System.Nullable<long> value);
    partial void OnPTCCompositionCRCChanged();
    partial void OnObjectCRCChanging(System.Nullable<long> value);
    partial void OnObjectCRCChanged();
    partial void OnAutoTagChanging(System.Nullable<bool> value);
    partial void OnAutoTagChanged();
    partial void OnTerritoryID2Changing(System.Nullable<int> value);
    partial void OnTerritoryID2Changed();
    partial void OnTerritoryID3Changing(System.Nullable<int> value);
    partial void OnTerritoryID3Changed();
    partial void OnCompList2Changing(string value);
    partial void OnCompList2Changed();
    partial void OnCompList3Changing(string value);
    partial void OnCompList3Changed();
    partial void OnFlagCompList1Changing(string value);
    partial void OnFlagCompList1Changed();
    partial void OnFlagCompList2Changing(string value);
    partial void OnFlagCompList2Changed();
    partial void OnFlagCompList3Changing(string value);
    partial void OnFlagCompList3Changed();
    partial void OnBorderFlagSubsChanging(string value);
    partial void OnBorderFlagSubsChanged();
    partial void OnBorderFlagCompListChanging(string value);
    partial void OnBorderFlagCompListChanged();
    partial void OnAutoTagStatusChanging(string value);
    partial void OnAutoTagStatusChanged();
    partial void OnCriticalAlertTypeChanging(System.Nullable<bool> value);
    partial void OnCriticalAlertTypeChanged();
    partial void OnIsPTCEnforceableChanging(bool value);
    partial void OnIsPTCEnforceableChanged();
    #endregion
		
		public tblTrackTagsActive()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackGUID", DbType="Int NOT NULL")]
		public int TrackGUID
		{
			get
			{
				return this._TrackGUID;
			}
			set
			{
				if ((this._TrackGUID != value))
				{
					this.OnTrackGUIDChanging(value);
					this.SendPropertyChanging();
					this._TrackGUID = value;
					this.SendPropertyChanged("TrackGUID");
					this.OnTrackGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subdivision", DbType="NVarChar(25)")]
		public string Subdivision
		{
			get
			{
				return this._Subdivision;
			}
			set
			{
				if ((this._Subdivision != value))
				{
					this.OnSubdivisionChanging(value);
					this.SendPropertyChanging();
					this._Subdivision = value;
					this.SendPropertyChanged("Subdivision");
					this.OnSubdivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryID", DbType="Int")]
		public System.Nullable<int> TerritoryID
		{
			get
			{
				return this._TerritoryID;
			}
			set
			{
				if ((this._TerritoryID != value))
				{
					this.OnTerritoryIDChanging(value);
					this.SendPropertyChanging();
					this._TerritoryID = value;
					this.SendPropertyChanged("TerritoryID");
					this.OnTerritoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="NVarChar(50)")]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="NVarChar(50)")]
		public string CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagType", DbType="NVarChar(50)")]
		public string TagType
		{
			get
			{
				return this._TagType;
			}
			set
			{
				if ((this._TagType != value))
				{
					this.OnTagTypeChanging(value);
					this.SendPropertyChanging();
					this._TagType = value;
					this.SendPropertyChanged("TagType");
					this.OnTagTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataString", DbType="NVarChar(MAX)")]
		public string DataString
		{
			get
			{
				return this._DataString;
			}
			set
			{
				if ((this._DataString != value))
				{
					this.OnDataStringChanging(value);
					this.SendPropertyChanging();
					this._DataString = value;
					this.SendPropertyChanged("DataString");
					this.OnDataStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Restrictive", DbType="Int")]
		public System.Nullable<int> Restrictive
		{
			get
			{
				return this._Restrictive;
			}
			set
			{
				if ((this._Restrictive != value))
				{
					this.OnRestrictiveChanging(value);
					this.SendPropertyChanging();
					this._Restrictive = value;
					this.SendPropertyChanged("Restrictive");
					this.OnRestrictiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestrictionFlag", DbType="Bit NOT NULL")]
		public bool RestrictionFlag
		{
			get
			{
				return this._RestrictionFlag;
			}
			set
			{
				if ((this._RestrictionFlag != value))
				{
					this.OnRestrictionFlagChanging(value);
					this.SendPropertyChanging();
					this._RestrictionFlag = value;
					this.SendPropertyChanged("RestrictionFlag");
					this.OnRestrictionFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelayData", DbType="NVarChar(MAX)")]
		public string DelayData
		{
			get
			{
				return this._DelayData;
			}
			set
			{
				if ((this._DelayData != value))
				{
					this.OnDelayDataChanging(value);
					this.SendPropertyChanging();
					this._DelayData = value;
					this.SendPropertyChanged("DelayData");
					this.OnDelayDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delay", DbType="Bit NOT NULL")]
		public bool Delay
		{
			get
			{
				return this._Delay;
			}
			set
			{
				if ((this._Delay != value))
				{
					this.OnDelayChanging(value);
					this.SendPropertyChanging();
					this._Delay = value;
					this.SendPropertyChanged("Delay");
					this.OnDelayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TagUID
		{
			get
			{
				return this._TagUID;
			}
			set
			{
				if ((this._TagUID != value))
				{
					this.OnTagUIDChanging(value);
					this.SendPropertyChanging();
					this._TagUID = value;
					this.SendPropertyChanged("TagUID");
					this.OnTagUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direction", DbType="NVarChar(10)")]
		public string Direction
		{
			get
			{
				return this._Direction;
			}
			set
			{
				if ((this._Direction != value))
				{
					this.OnDirectionChanging(value);
					this.SendPropertyChanging();
					this._Direction = value;
					this.SendPropertyChanged("Direction");
					this.OnDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedReleaseTime", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ExpectedReleaseTime
		{
			get
			{
				return this._ExpectedReleaseTime;
			}
			set
			{
				if ((this._ExpectedReleaseTime != value))
				{
					this.OnExpectedReleaseTimeChanging(value);
					this.SendPropertyChanging();
					this._ExpectedReleaseTime = value;
					this.SendPropertyChanged("ExpectedReleaseTime");
					this.OnExpectedReleaseTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompList", DbType="NVarChar(4000)")]
		public string CompList
		{
			get
			{
				return this._CompList;
			}
			set
			{
				if ((this._CompList != value))
				{
					this.OnCompListChanging(value);
					this.SendPropertyChanging();
					this._CompList = value;
					this.SendPropertyChanged("CompList");
					this.OnCompListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNumPTC", DbType="Int")]
		public System.Nullable<int> RefNumPTC
		{
			get
			{
				return this._RefNumPTC;
			}
			set
			{
				if ((this._RefNumPTC != value))
				{
					this.OnRefNumPTCChanging(value);
					this.SendPropertyChanging();
					this._RefNumPTC = value;
					this.SendPropertyChanged("RefNumPTC");
					this.OnRefNumPTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTCData", DbType="NVarChar(1000)")]
		public string PTCData
		{
			get
			{
				return this._PTCData;
			}
			set
			{
				if ((this._PTCData != value))
				{
					this.OnPTCDataChanging(value);
					this.SendPropertyChanging();
					this._PTCData = value;
					this.SendPropertyChanged("PTCData");
					this.OnPTCDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRequestingTagPlacement", DbType="NVarChar(50)")]
		public string NameRequestingTagPlacement
		{
			get
			{
				return this._NameRequestingTagPlacement;
			}
			set
			{
				if ((this._NameRequestingTagPlacement != value))
				{
					this.OnNameRequestingTagPlacementChanging(value);
					this.SendPropertyChanging();
					this._NameRequestingTagPlacement = value;
					this.SendPropertyChanged("NameRequestingTagPlacement");
					this.OnNameRequestingTagPlacementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpeedTagFlagInfo", DbType="NVarChar(500)")]
		public string SpeedTagFlagInfo
		{
			get
			{
				return this._SpeedTagFlagInfo;
			}
			set
			{
				if ((this._SpeedTagFlagInfo != value))
				{
					this.OnSpeedTagFlagInfoChanging(value);
					this.SendPropertyChanging();
					this._SpeedTagFlagInfo = value;
					this.SendPropertyChanged("SpeedTagFlagInfo");
					this.OnSpeedTagFlagInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpeedTagReasonCode", DbType="NVarChar(50)")]
		public string SpeedTagReasonCode
		{
			get
			{
				return this._SpeedTagReasonCode;
			}
			set
			{
				if ((this._SpeedTagReasonCode != value))
				{
					this.OnSpeedTagReasonCodeChanging(value);
					this.SendPropertyChanging();
					this._SpeedTagReasonCode = value;
					this.SendPropertyChanged("SpeedTagReasonCode");
					this.OnSpeedTagReasonCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateSpeedRestriction", DbType="Bit")]
		public System.Nullable<bool> CreateSpeedRestriction
		{
			get
			{
				return this._CreateSpeedRestriction;
			}
			set
			{
				if ((this._CreateSpeedRestriction != value))
				{
					this.OnCreateSpeedRestrictionChanging(value);
					this.SendPropertyChanging();
					this._CreateSpeedRestriction = value;
					this.SendPropertyChanged("CreateSpeedRestriction");
					this.OnCreateSpeedRestrictionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpeedRestrictionCreated", DbType="Bit")]
		public System.Nullable<bool> SpeedRestrictionCreated
		{
			get
			{
				return this._SpeedRestrictionCreated;
			}
			set
			{
				if ((this._SpeedRestrictionCreated != value))
				{
					this.OnSpeedRestrictionCreatedChanging(value);
					this.SendPropertyChanging();
					this._SpeedRestrictionCreated = value;
					this.SendPropertyChanged("SpeedRestrictionCreated");
					this.OnSpeedRestrictionCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationTime", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DurationTime
		{
			get
			{
				return this._DurationTime;
			}
			set
			{
				if ((this._DurationTime != value))
				{
					this.OnDurationTimeChanging(value);
					this.SendPropertyChanging();
					this._DurationTime = value;
					this.SendPropertyChanged("DurationTime");
					this.OnDurationTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BulletinTag", DbType="Bit")]
		public System.Nullable<bool> BulletinTag
		{
			get
			{
				return this._BulletinTag;
			}
			set
			{
				if ((this._BulletinTag != value))
				{
					this.OnBulletinTagChanging(value);
					this.SendPropertyChanging();
					this._BulletinTag = value;
					this.SendPropertyChanged("BulletinTag");
					this.OnBulletinTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BulletinReferenceGUID", DbType="NVarChar(50)")]
		public string BulletinReferenceGUID
		{
			get
			{
				return this._BulletinReferenceGUID;
			}
			set
			{
				if ((this._BulletinReferenceGUID != value))
				{
					this.OnBulletinReferenceGUIDChanging(value);
					this.SendPropertyChanging();
					this._BulletinReferenceGUID = value;
					this.SendPropertyChanged("BulletinReferenceGUID");
					this.OnBulletinReferenceGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BulletinForProtectionList", DbType="Bit")]
		public System.Nullable<bool> BulletinForProtectionList
		{
			get
			{
				return this._BulletinForProtectionList;
			}
			set
			{
				if ((this._BulletinForProtectionList != value))
				{
					this.OnBulletinForProtectionListChanging(value);
					this.SendPropertyChanging();
					this._BulletinForProtectionList = value;
					this.SendPropertyChanged("BulletinForProtectionList");
					this.OnBulletinForProtectionListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BulletinForCancellationList", DbType="Bit")]
		public System.Nullable<bool> BulletinForCancellationList
		{
			get
			{
				return this._BulletinForCancellationList;
			}
			set
			{
				if ((this._BulletinForCancellationList != value))
				{
					this.OnBulletinForCancellationListChanging(value);
					this.SendPropertyChanging();
					this._BulletinForCancellationList = value;
					this.SendPropertyChanged("BulletinForCancellationList");
					this.OnBulletinForCancellationListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTCComponents", DbType="NVarChar(4000)")]
		public string PTCComponents
		{
			get
			{
				return this._PTCComponents;
			}
			set
			{
				if ((this._PTCComponents != value))
				{
					this.OnPTCComponentsChanging(value);
					this.SendPropertyChanging();
					this._PTCComponents = value;
					this.SendPropertyChanged("PTCComponents");
					this.OnPTCComponentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTCTrackSegments", DbType="NVarChar(2000)")]
		public string PTCTrackSegments
		{
			get
			{
				return this._PTCTrackSegments;
			}
			set
			{
				if ((this._PTCTrackSegments != value))
				{
					this.OnPTCTrackSegmentsChanging(value);
					this.SendPropertyChanging();
					this._PTCTrackSegments = value;
					this.SendPropertyChanged("PTCTrackSegments");
					this.OnPTCTrackSegmentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTCBulletinText", DbType="NVarChar(4000)")]
		public string PTCBulletinText
		{
			get
			{
				return this._PTCBulletinText;
			}
			set
			{
				if ((this._PTCBulletinText != value))
				{
					this.OnPTCBulletinTextChanging(value);
					this.SendPropertyChanging();
					this._PTCBulletinText = value;
					this.SendPropertyChanged("PTCBulletinText");
					this.OnPTCBulletinTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilePostBeginPrefix", DbType="NVarChar(5)")]
		public string MilePostBeginPrefix
		{
			get
			{
				return this._MilePostBeginPrefix;
			}
			set
			{
				if ((this._MilePostBeginPrefix != value))
				{
					this.OnMilePostBeginPrefixChanging(value);
					this.SendPropertyChanging();
					this._MilePostBeginPrefix = value;
					this.SendPropertyChanged("MilePostBeginPrefix");
					this.OnMilePostBeginPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilePostEndPrefix", DbType="NVarChar(5)")]
		public string MilePostEndPrefix
		{
			get
			{
				return this._MilePostEndPrefix;
			}
			set
			{
				if ((this._MilePostEndPrefix != value))
				{
					this.OnMilePostEndPrefixChanging(value);
					this.SendPropertyChanging();
					this._MilePostEndPrefix = value;
					this.SendPropertyChanged("MilePostEndPrefix");
					this.OnMilePostEndPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryOfRestriction", DbType="NVarChar(MAX)")]
		public string DeliveryOfRestriction
		{
			get
			{
				return this._DeliveryOfRestriction;
			}
			set
			{
				if ((this._DeliveryOfRestriction != value))
				{
					this.OnDeliveryOfRestrictionChanging(value);
					this.SendPropertyChanging();
					this._DeliveryOfRestriction = value;
					this.SendPropertyChanged("DeliveryOfRestriction");
					this.OnDeliveryOfRestrictionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvisorySummary", DbType="NVarChar(50)")]
		public string AdvisorySummary
		{
			get
			{
				return this._AdvisorySummary;
			}
			set
			{
				if ((this._AdvisorySummary != value))
				{
					this.OnAdvisorySummaryChanging(value);
					this.SendPropertyChanging();
					this._AdvisorySummary = value;
					this.SendPropertyChanged("AdvisorySummary");
					this.OnAdvisorySummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilePostBeginSuffix", DbType="NVarChar(5)")]
		public string MilePostBeginSuffix
		{
			get
			{
				return this._MilePostBeginSuffix;
			}
			set
			{
				if ((this._MilePostBeginSuffix != value))
				{
					this.OnMilePostBeginSuffixChanging(value);
					this.SendPropertyChanging();
					this._MilePostBeginSuffix = value;
					this.SendPropertyChanged("MilePostBeginSuffix");
					this.OnMilePostBeginSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilePostEndSuffix", DbType="NVarChar(5)")]
		public string MilePostEndSuffix
		{
			get
			{
				return this._MilePostEndSuffix;
			}
			set
			{
				if ((this._MilePostEndSuffix != value))
				{
					this.OnMilePostEndSuffixChanging(value);
					this.SendPropertyChanging();
					this._MilePostEndSuffix = value;
					this.SendPropertyChanged("MilePostEndSuffix");
					this.OnMilePostEndSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilePostBegin", DbType="NVarChar(10)")]
		public string MilePostBegin
		{
			get
			{
				return this._MilePostBegin;
			}
			set
			{
				if ((this._MilePostBegin != value))
				{
					this.OnMilePostBeginChanging(value);
					this.SendPropertyChanging();
					this._MilePostBegin = value;
					this.SendPropertyChanged("MilePostBegin");
					this.OnMilePostBeginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilePostEnd", DbType="NVarChar(10)")]
		public string MilePostEnd
		{
			get
			{
				return this._MilePostEnd;
			}
			set
			{
				if ((this._MilePostEnd != value))
				{
					this.OnMilePostEndChanging(value);
					this.SendPropertyChanging();
					this._MilePostEnd = value;
					this.SendPropertyChanged("MilePostEnd");
					this.OnMilePostEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTCCompositionCRC", DbType="BigInt")]
		public System.Nullable<long> PTCCompositionCRC
		{
			get
			{
				return this._PTCCompositionCRC;
			}
			set
			{
				if ((this._PTCCompositionCRC != value))
				{
					this.OnPTCCompositionCRCChanging(value);
					this.SendPropertyChanging();
					this._PTCCompositionCRC = value;
					this.SendPropertyChanged("PTCCompositionCRC");
					this.OnPTCCompositionCRCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectCRC", DbType="BigInt")]
		public System.Nullable<long> ObjectCRC
		{
			get
			{
				return this._ObjectCRC;
			}
			set
			{
				if ((this._ObjectCRC != value))
				{
					this.OnObjectCRCChanging(value);
					this.SendPropertyChanging();
					this._ObjectCRC = value;
					this.SendPropertyChanged("ObjectCRC");
					this.OnObjectCRCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoTag", DbType="Bit")]
		public System.Nullable<bool> AutoTag
		{
			get
			{
				return this._AutoTag;
			}
			set
			{
				if ((this._AutoTag != value))
				{
					this.OnAutoTagChanging(value);
					this.SendPropertyChanging();
					this._AutoTag = value;
					this.SendPropertyChanged("AutoTag");
					this.OnAutoTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryID2", DbType="Int")]
		public System.Nullable<int> TerritoryID2
		{
			get
			{
				return this._TerritoryID2;
			}
			set
			{
				if ((this._TerritoryID2 != value))
				{
					this.OnTerritoryID2Changing(value);
					this.SendPropertyChanging();
					this._TerritoryID2 = value;
					this.SendPropertyChanged("TerritoryID2");
					this.OnTerritoryID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryID3", DbType="Int")]
		public System.Nullable<int> TerritoryID3
		{
			get
			{
				return this._TerritoryID3;
			}
			set
			{
				if ((this._TerritoryID3 != value))
				{
					this.OnTerritoryID3Changing(value);
					this.SendPropertyChanging();
					this._TerritoryID3 = value;
					this.SendPropertyChanged("TerritoryID3");
					this.OnTerritoryID3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompList2", DbType="NVarChar(4000)")]
		public string CompList2
		{
			get
			{
				return this._CompList2;
			}
			set
			{
				if ((this._CompList2 != value))
				{
					this.OnCompList2Changing(value);
					this.SendPropertyChanging();
					this._CompList2 = value;
					this.SendPropertyChanged("CompList2");
					this.OnCompList2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompList3", DbType="NVarChar(4000)")]
		public string CompList3
		{
			get
			{
				return this._CompList3;
			}
			set
			{
				if ((this._CompList3 != value))
				{
					this.OnCompList3Changing(value);
					this.SendPropertyChanging();
					this._CompList3 = value;
					this.SendPropertyChanged("CompList3");
					this.OnCompList3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagCompList1", DbType="NVarChar(4000)")]
		public string FlagCompList1
		{
			get
			{
				return this._FlagCompList1;
			}
			set
			{
				if ((this._FlagCompList1 != value))
				{
					this.OnFlagCompList1Changing(value);
					this.SendPropertyChanging();
					this._FlagCompList1 = value;
					this.SendPropertyChanged("FlagCompList1");
					this.OnFlagCompList1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagCompList2", DbType="NVarChar(4000)")]
		public string FlagCompList2
		{
			get
			{
				return this._FlagCompList2;
			}
			set
			{
				if ((this._FlagCompList2 != value))
				{
					this.OnFlagCompList2Changing(value);
					this.SendPropertyChanging();
					this._FlagCompList2 = value;
					this.SendPropertyChanged("FlagCompList2");
					this.OnFlagCompList2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagCompList3", DbType="NVarChar(4000)")]
		public string FlagCompList3
		{
			get
			{
				return this._FlagCompList3;
			}
			set
			{
				if ((this._FlagCompList3 != value))
				{
					this.OnFlagCompList3Changing(value);
					this.SendPropertyChanging();
					this._FlagCompList3 = value;
					this.SendPropertyChanged("FlagCompList3");
					this.OnFlagCompList3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorderFlagSubs", DbType="NVarChar(50)")]
		public string BorderFlagSubs
		{
			get
			{
				return this._BorderFlagSubs;
			}
			set
			{
				if ((this._BorderFlagSubs != value))
				{
					this.OnBorderFlagSubsChanging(value);
					this.SendPropertyChanging();
					this._BorderFlagSubs = value;
					this.SendPropertyChanged("BorderFlagSubs");
					this.OnBorderFlagSubsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorderFlagCompList", DbType="NVarChar(2000)")]
		public string BorderFlagCompList
		{
			get
			{
				return this._BorderFlagCompList;
			}
			set
			{
				if ((this._BorderFlagCompList != value))
				{
					this.OnBorderFlagCompListChanging(value);
					this.SendPropertyChanging();
					this._BorderFlagCompList = value;
					this.SendPropertyChanged("BorderFlagCompList");
					this.OnBorderFlagCompListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoTagStatus", DbType="NVarChar(50)")]
		public string AutoTagStatus
		{
			get
			{
				return this._AutoTagStatus;
			}
			set
			{
				if ((this._AutoTagStatus != value))
				{
					this.OnAutoTagStatusChanging(value);
					this.SendPropertyChanging();
					this._AutoTagStatus = value;
					this.SendPropertyChanged("AutoTagStatus");
					this.OnAutoTagStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriticalAlertType", DbType="Bit")]
		public System.Nullable<bool> CriticalAlertType
		{
			get
			{
				return this._CriticalAlertType;
			}
			set
			{
				if ((this._CriticalAlertType != value))
				{
					this.OnCriticalAlertTypeChanging(value);
					this.SendPropertyChanging();
					this._CriticalAlertType = value;
					this.SendPropertyChanged("CriticalAlertType");
					this.OnCriticalAlertTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPTCEnforceable", DbType="Bit NOT NULL")]
		public bool IsPTCEnforceable
		{
			get
			{
				return this._IsPTCEnforceable;
			}
			set
			{
				if ((this._IsPTCEnforceable != value))
				{
					this.OnIsPTCEnforceableChanging(value);
					this.SendPropertyChanging();
					this._IsPTCEnforceable = value;
					this.SendPropertyChanged("IsPTCEnforceable");
					this.OnIsPTCEnforceableChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
